version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\OzqurYalcin\parasut

environment:
  GOPATH: c:\gopath

install:
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env
  - go get -v -t -d ./...

build_script:
  - go test -v ./...
